// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// FF
double FF(NumericMatrix dta);
RcppExport SEXP _MDgof_FF(SEXP dtaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dta(dtaSEXP);
    rcpp_result_gen = Rcpp::wrap(FF(dta));
    return rcpp_result_gen;
END_RCPP
}
// TS_cont
Rcpp::NumericVector TS_cont(Rcpp::NumericMatrix x, Rcpp::Function pnull, Rcpp::NumericVector param, Rcpp::List TSextra);
RcppExport SEXP _MDgof_TS_cont(SEXP xSEXP, SEXP pnullSEXP, SEXP paramSEXP, SEXP TSextraSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type pnull(pnullSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type param(paramSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type TSextra(TSextraSEXP);
    rcpp_result_gen = Rcpp::wrap(TS_cont(x, pnull, param, TSextra));
    return rcpp_result_gen;
END_RCPP
}
// TS_disc
Rcpp::NumericVector TS_disc(Rcpp::NumericMatrix x, Rcpp::Function pnull, Rcpp::NumericVector param, Rcpp::List TSextra);
RcppExport SEXP _MDgof_TS_disc(SEXP xSEXP, SEXP pnullSEXP, SEXP paramSEXP, SEXP TSextraSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type pnull(pnullSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type param(paramSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type TSextra(TSextraSEXP);
    rcpp_result_gen = Rcpp::wrap(TS_disc(x, pnull, param, TSextra));
    return rcpp_result_gen;
END_RCPP
}
// gen_eval
NumericMatrix gen_eval(Function rnull, NumericVector p, int m);
RcppExport SEXP _MDgof_gen_eval(SEXP rnullSEXP, SEXP pSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type rnull(rnullSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(gen_eval(rnull, p, m));
    return rcpp_result_gen;
END_RCPP
}
// gauss_kernel_matrix
NumericMatrix gauss_kernel_matrix(const NumericMatrix& Eval, const NumericMatrix& S, double h);
RcppExport SEXP _MDgof_gauss_kernel_matrix(SEXP EvalSEXP, SEXP SSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Eval(EvalSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type S(SSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(gauss_kernel_matrix(Eval, S, h));
    return rcpp_result_gen;
END_RCPP
}
// estimateEV
List estimateEV(Function rnull, NumericVector p, const NumericMatrix& Eval, double h, int nsim_mc, int n);
RcppExport SEXP _MDgof_estimateEV(SEXP rnullSEXP, SEXP pSEXP, SEXP EvalSEXP, SEXP hSEXP, SEXP nsim_mcSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type rnull(rnullSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Eval(EvalSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< int >::type nsim_mc(nsim_mcSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(estimateEV(rnull, p, Eval, h, nsim_mc, n));
    return rcpp_result_gen;
END_RCPP
}
// compute_M_for_dtaset
double compute_M_for_dtaset(const NumericMatrix& dta, const NumericMatrix& Eval, const NumericVector& hs, Function rnull, NumericVector p, int nsim_mc);
RcppExport SEXP _MDgof_compute_M_for_dtaset(SEXP dtaSEXP, SEXP EvalSEXP, SEXP hsSEXP, SEXP rnullSEXP, SEXP pSEXP, SEXP nsim_mcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type dta(dtaSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Eval(EvalSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type hs(hsSEXP);
    Rcpp::traits::input_parameter< Function >::type rnull(rnullSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type nsim_mc(nsim_mcSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_M_for_dtaset(dta, Eval, hs, rnull, p, nsim_mc));
    return rcpp_result_gen;
END_RCPP
}
// bakshaev_rudzkis
List bakshaev_rudzkis(NumericMatrix dta, Function rnull, NumericVector p, int m_eval, int nsim, int nsim_mc);
RcppExport SEXP _MDgof_bakshaev_rudzkis(SEXP dtaSEXP, SEXP rnullSEXP, SEXP pSEXP, SEXP m_evalSEXP, SEXP nsimSEXP, SEXP nsim_mcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dta(dtaSEXP);
    Rcpp::traits::input_parameter< Function >::type rnull(rnullSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type m_eval(m_evalSEXP);
    Rcpp::traits::input_parameter< int >::type nsim(nsimSEXP);
    Rcpp::traits::input_parameter< int >::type nsim_mc(nsim_mcSEXP);
    rcpp_result_gen = Rcpp::wrap(bakshaev_rudzkis(dta, rnull, p, m_eval, nsim, nsim_mc));
    return rcpp_result_gen;
END_RCPP
}
// calcTS
NumericVector calcTS(Rcpp::NumericMatrix dta, Rcpp::Function TS, int typeTS, Rcpp::List TSextra);
RcppExport SEXP _MDgof_calcTS(SEXP dtaSEXP, SEXP TSSEXP, SEXP typeTSSEXP, SEXP TSextraSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type dta(dtaSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type TS(TSSEXP);
    Rcpp::traits::input_parameter< int >::type typeTS(typeTSSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type TSextra(TSextraSEXP);
    rcpp_result_gen = Rcpp::wrap(calcTS(dta, TS, typeTS, TSextra));
    return rcpp_result_gen;
END_RCPP
}
// discretize
Rcpp::NumericMatrix discretize(Rcpp::NumericMatrix x, Rcpp::NumericMatrix Range, Rcpp::NumericVector nbins, bool ChangeVals);
RcppExport SEXP _MDgof_discretize(SEXP xSEXP, SEXP RangeSEXP, SEXP nbinsSEXP, SEXP ChangeValsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Range(RangeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type nbins(nbinsSEXP);
    Rcpp::traits::input_parameter< bool >::type ChangeVals(ChangeValsSEXP);
    rcpp_result_gen = Rcpp::wrap(discretize(x, Range, nbins, ChangeVals));
    return rcpp_result_gen;
END_RCPP
}
// ksd
double ksd(NumericMatrix X, Function scf, NumericVector p);
RcppExport SEXP _MDgof_ksd(SEXP XSEXP, SEXP scfSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< Function >::type scf(scfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(ksd(X, scf, p));
    return rcpp_result_gen;
END_RCPP
}
// mdecdf
NumericVector mdecdf(NumericMatrix dta, NumericMatrix pts);
RcppExport SEXP _MDgof_mdecdf(SEXP dtaSEXP, SEXP ptsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dta(dtaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pts(ptsSEXP);
    rcpp_result_gen = Rcpp::wrap(mdecdf(dta, pts));
    return rcpp_result_gen;
END_RCPP
}
// mmd
double mmd(NumericMatrix x, Function rnull, NumericVector p);
RcppExport SEXP _MDgof_mmd(SEXP xSEXP, SEXP rnullSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< Function >::type rnull(rnullSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(mmd(x, rnull, p));
    return rcpp_result_gen;
END_RCPP
}
// grad_vec
NumericVector grad_vec(NumericVector x, Function f);
RcppExport SEXP _MDgof_grad_vec(SEXP xSEXP, SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Function >::type f(fSEXP);
    rcpp_result_gen = Rcpp::wrap(grad_vec(x, f));
    return rcpp_result_gen;
END_RCPP
}
// grad_mat
NumericMatrix grad_mat(NumericMatrix x, Function f);
RcppExport SEXP _MDgof_grad_mat(SEXP xSEXP, SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< Function >::type f(fSEXP);
    rcpp_result_gen = Rcpp::wrap(grad_mat(x, f));
    return rcpp_result_gen;
END_RCPP
}
// orderC
Rcpp::IntegerVector orderC(Rcpp::NumericVector x, Rcpp::NumericVector y);
RcppExport SEXP _MDgof_orderC(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(orderC(x, y));
    return rcpp_result_gen;
END_RCPP
}
// p2dC
Rcpp::NumericMatrix p2dC(Rcpp::NumericMatrix x, Rcpp::Function cdf, Rcpp::NumericVector p, Rcpp::NumericVector Fx);
RcppExport SEXP _MDgof_p2dC(SEXP xSEXP, SEXP cdfSEXP, SEXP pSEXP, SEXP FxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type cdf(cdfSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Fx(FxSEXP);
    rcpp_result_gen = Rcpp::wrap(p2dC(x, cdf, p, Fx));
    return rcpp_result_gen;
END_RCPP
}
// powerC
Rcpp::List powerC(Rcpp::Function rnull, Rcpp::Function ralt, Rcpp::NumericVector param_alt, Rcpp::Function TS, int typeTS, Rcpp::List TSextra, const int B);
RcppExport SEXP _MDgof_powerC(SEXP rnullSEXP, SEXP raltSEXP, SEXP param_altSEXP, SEXP TSSEXP, SEXP typeTSSEXP, SEXP TSextraSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Function >::type rnull(rnullSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type ralt(raltSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type param_alt(param_altSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type TS(TSSEXP);
    Rcpp::traits::input_parameter< int >::type typeTS(typeTSSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type TSextra(TSextraSEXP);
    Rcpp::traits::input_parameter< const int >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(powerC(rnull, ralt, param_alt, TS, typeTS, TSextra, B));
    return rcpp_result_gen;
END_RCPP
}
// rosenblattC
NumericMatrix rosenblattC(NumericMatrix x, Function cdf, NumericVector p, NumericMatrix Range);
RcppExport SEXP _MDgof_rosenblattC(SEXP xSEXP, SEXP cdfSEXP, SEXP pSEXP, SEXP RangeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< Function >::type cdf(cdfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Range(RangeSEXP);
    rcpp_result_gen = Rcpp::wrap(rosenblattC(x, cdf, p, Range));
    return rcpp_result_gen;
END_RCPP
}
// testC
Rcpp::NumericMatrix testC(Rcpp::NumericMatrix dta, Rcpp::Function rnull, Rcpp::Function TS, int typeTS, Rcpp::List TSextra, int B);
RcppExport SEXP _MDgof_testC(SEXP dtaSEXP, SEXP rnullSEXP, SEXP TSSEXP, SEXP typeTSSEXP, SEXP TSextraSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type dta(dtaSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type rnull(rnullSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type TS(TSSEXP);
    Rcpp::traits::input_parameter< int >::type typeTS(typeTSSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type TSextra(TSextraSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(testC(dta, rnull, TS, typeTS, TSextra, B));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MDgof_FF", (DL_FUNC) &_MDgof_FF, 1},
    {"_MDgof_TS_cont", (DL_FUNC) &_MDgof_TS_cont, 4},
    {"_MDgof_TS_disc", (DL_FUNC) &_MDgof_TS_disc, 4},
    {"_MDgof_gen_eval", (DL_FUNC) &_MDgof_gen_eval, 3},
    {"_MDgof_gauss_kernel_matrix", (DL_FUNC) &_MDgof_gauss_kernel_matrix, 3},
    {"_MDgof_estimateEV", (DL_FUNC) &_MDgof_estimateEV, 6},
    {"_MDgof_compute_M_for_dtaset", (DL_FUNC) &_MDgof_compute_M_for_dtaset, 6},
    {"_MDgof_bakshaev_rudzkis", (DL_FUNC) &_MDgof_bakshaev_rudzkis, 6},
    {"_MDgof_calcTS", (DL_FUNC) &_MDgof_calcTS, 4},
    {"_MDgof_discretize", (DL_FUNC) &_MDgof_discretize, 4},
    {"_MDgof_ksd", (DL_FUNC) &_MDgof_ksd, 3},
    {"_MDgof_mdecdf", (DL_FUNC) &_MDgof_mdecdf, 2},
    {"_MDgof_mmd", (DL_FUNC) &_MDgof_mmd, 3},
    {"_MDgof_grad_vec", (DL_FUNC) &_MDgof_grad_vec, 2},
    {"_MDgof_grad_mat", (DL_FUNC) &_MDgof_grad_mat, 2},
    {"_MDgof_orderC", (DL_FUNC) &_MDgof_orderC, 2},
    {"_MDgof_p2dC", (DL_FUNC) &_MDgof_p2dC, 4},
    {"_MDgof_powerC", (DL_FUNC) &_MDgof_powerC, 7},
    {"_MDgof_rosenblattC", (DL_FUNC) &_MDgof_rosenblattC, 4},
    {"_MDgof_testC", (DL_FUNC) &_MDgof_testC, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_MDgof(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
